### ISSUE TITLE
Why this code.

### ISSUE THREAD

**Issue by mullayilkannan** [NourozR/Stock-Price-Prediction-of-Apple-Inc.-Using-Recurrent-Neural-Network-#1]
last_val = testPredict[-1]
last_val_scaled = last_val/last_val
Why not just give 
last_val_scaled=1

**Comment by NourozR** [comment]
This was redundant. Will fix it and add codes for prediction in a function very soon. Thanks!

**Comment by prakashjj** [comment]
Hi...thank you for the great code. Thought it looks great when plotted I am not sure how to predict the future values. As this is the timeseries data shouldn't we apply the model on a series of data and not just one last value to get the prediction.

**Comment by NourozR** [comment]
Yes. I will update the code soon. I don't have a good computing platform right now - when I do, I will. Thanks for the comment and reminder.

**Comment by CarloBernardi** [comment]
Hi Nowruz, this study is interesting and exciting me! Waiting for new features for easy predictions on timeseries. Good Luck!

**Comment by NourozR** [comment]
Thanks @CarloBernardi !

**Comment by Zhenhualuo** [comment]
These codes are awesome! Then how to modify the codes to predict next week or month's price?

**Comment by NourozR** [comment]
@Zhenhualuo will update the code or come up with another project that predicts future values. Thanks!
