### ISSUE TITLE
This model no longer produces accurate predictions.

### ISSUE THREAD

**Issue by HourGlss** [NourozR/Stock-Price-Prediction-of-Apple-Inc.-Using-Recurrent-Neural-Network-#11]
I believe this may be an issue with keras / tensorflow updating, and not a 'code' problem.

> absl-py==0.11.0
> astunparse==1.6.3
> cachetools==4.2.1
> certifi==2020.12.5
> chardet==4.0.0
> cycler==0.10.0
> flatbuffers==1.12
> gast==0.3.3
> google-auth==1.27.0
> google-auth-oauthlib==0.4.2
> google-pasta==0.2.0
> grpcio==1.32.0
> h5py==2.10.0
> idna==3.1
> joblib==1.0.1
> Keras==2.4.3
> Keras-Preprocessing==1.1.2
> kiwisolver==1.3.1
> Markdown==3.3.4
> matplotlib==3.3.4
> mplfinance==0.12.7a7
> numpy==1.19.5
> oauthlib==3.1.0
> opt-einsum==3.3.0
> pandas==1.2.2
> Pillow==8.1.0
> protobuf==3.15.3
> pyasn1==0.4.8
> pyasn1-modules==0.2.8
> pyparsing==2.4.7
> python-dateutil==2.8.1
> pytz==2021.1
> PyYAML==5.4.1
> requests==2.25.1
> requests-oauthlib==1.3.0
> rsa==4.7.2
> scikit-learn==0.24.1
> scipy==1.6.1
> six==1.15.0
> tensorboard==2.4.1
> tensorboard-plugin-wit==1.8.0
> tensorflow==2.4.1
> tensorflow-estimator==2.4.0
> termcolor==1.1.0
> threadpoolctl==2.1.0
> typing-extensions==3.7.4.3
> urllib3==1.26.3
> Werkzeug==1.0.1
> wrapt==1.12.1

![image](https://user-images.githubusercontent.com/1668760/109514787-638e5780-7a74-11eb-9868-f0f67855a65b.png)

No errors of any kind, please advise.

**Comment by stylepatrick** [comment]
Hello, i am having exactly the same issue. How can we solve it?

**Comment by boozesounds** [comment]
The same is true of me.

**Comment by stylepatrick** [comment]
I found a way which works with newest version:
https://github.com/stylepatrick/trading-price-prediction

 If you like please give a star.

**Comment by NourozR** [comment]
This is a very old code, please use recent syntax and check the documentation of Keras. That should help!

**Comment by Crescent617** [comment]
maybe this is due to the epoch of training is only 5...
