### ISSUE TITLE
Mistake in Code

### ISSUE THREAD

**Issue by YuQuankun** [NourozR/Stock-Price-Prediction-of-Apple-Inc.-Using-Recurrent-Neural-Network-#12]
There is a big mistake in your code. In the StockPrediction.py , model.add('linear') is not right. We all know that the activation function have to be not linear, the linear activation will make the perdiction not right.

**Comment by NourozR** [comment]
I disagree. Please check the documentation of LSTM better. Hopefully that would help you. Thank you!
