### ISSUE TITLE
The outout predection is not good right 

### ISSUE THREAD

**Issue by akashcse** [NourozR/Stock-Price-Prediction-of-Apple-Inc.-Using-Recurrent-Neural-Network-#15]
Last Day Value: 77.23725128173828
Next Day Value: 21.601646423339844

**Comment by NourozR** [comment]
I coded this a long back and these days I don't really work on LSTMs anymore. Hence, I am sorry to let you know that I don't have the capacity to have a look at this anymore. Naturally this code is very old and few things might not work anymore.
