### ISSUE TITLE
Add More Features?

### ISSUE THREAD

**Issue by boxxa** [NourozR/Stock-Price-Prediction-of-Apple-Inc.-Using-Recurrent-Neural-Network-#3]
This is awesome and helpful. I have been playing with it and have RMSE down on test data under 1. If I am reading the output right, it displays the previous days average you are using and then the next days prediction? Is there a way to look ahead more steps? 

Also, you are taking the OHLC and turning it into a 1 value input. Is there a way to use this model to add more inputs such as features on top of the OHLC value?

**Comment by NourozR** [comment]
I also have plans to do predictions for many steps. Would add it. 

This is an example of univariate time-series prediction, so only 1D features were used. You could try it for a multivariate scenario. 

Thanks!
