### ISSUE TITLE
Measuring error

### ISSUE THREAD

**Issue by fedecaccia** [NourozR/Stock-Price-Prediction-of-Apple-Inc.-Using-Recurrent-Neural-Network-#4]
Nice work! I have a suggest:
You are testing the model with RMSE this way:

testScore = math.sqrt(mean_squared_error(testY[0], testPredict[:,0]))

which is not a good metric to quantify the accuracy neither the performance of the model. Much more important that RMSE is the ability of the model to predict stock movements.
So I would like to see some metrics taking into account how much ups and downs are efficiently predicted. I suggest to implement [recall and prediction](https://en.wikipedia.org/wiki/Precision_and_recall) measurements.

**Comment by NourozR** [comment]
You need to check the basic kinds of stuff once again bro. It's a regression work, FYI.
