### ISSUE TITLE
Wrong Prediction

### ISSUE THREAD

**Issue by leodennis** [NourozR/Stock-Price-Prediction-of-Apple-Inc.-Using-Recurrent-Neural-Network-#5]
Hi,

nice post but the results are wrong.

You are not predicting some days ahead but only one day ahead at a time.
You are not taking your prediction as input for your next prediciton, but you are taking the actual value.

This results in a lag of the actual signal, all your network has to do is produce a similar value to the last input of the price.

If you would take your prediction as the input for the next prediction you would see that the results are quite bad…

I see lot’s of LSTM price prediction examples but they all seem to be wrong and I don’t think it is possible to predict accuratly the next prices.

**Comment by NourozR** [comment]
I think your whole idea about prediction is wrong bro.

**Comment by Apostatee** [comment]
> I think your whole idea about prediction is wrong bro.

He was right, you could always get better results just use the price of the last day. You can try predicting the return instead
